/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountSessionsRouteImport } from './routes/account/sessions'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountDataRouteImport } from './routes/account/data'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthMagicRouteImport } from './routes/_auth/magic'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppInvitationsRouteImport } from './routes/_app/invitations'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppUsersSessionsRouteImport } from './routes/_app/users/sessions'
import { Route as AppUsersInvitationsRouteImport } from './routes/_app/users/invitations'
import { Route as AppUsersImportRouteImport } from './routes/_app/users/import'
import { Route as AppUsersDeletedRouteImport } from './routes/_app/users/deleted'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppSettingsBrandingRouteImport } from './routes/_app/settings/branding'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSecuritySessionsRouteImport } from './routes/_app/security/sessions'
import { Route as AppSecurityRateLimitsRouteImport } from './routes/_app/security/rate-limits'
import { Route as AppSecurityAuditLogsRouteImport } from './routes/_app/security/audit-logs'
import { Route as AppOrganizationsTenantsRouteImport } from './routes/_app/organizations/tenants'
import { Route as AppOrganizationsMembersRouteImport } from './routes/_app/organizations/members'
import { Route as AppDeveloperWebhooksRouteImport } from './routes/_app/developer/webhooks'
import { Route as AppDeveloperInfrastructureRouteImport } from './routes/_app/developer/infrastructure'
import { Route as AppDeveloperBotsRouteImport } from './routes/_app/developer/bots'
import { Route as AppAuthSocialRouteImport } from './routes/_app/auth/social'
import { Route as AppAccessRolesRouteImport } from './routes/_app/access/roles'
import { Route as AppAccessResourcesRouteImport } from './routes/_app/access/resources'
import { Route as AppAccessPoliciesRouteImport } from './routes/_app/access/policies'
import { Route as AppAccessPermissionsRouteImport } from './routes/_app/access/permissions'
import { Route as AppSettingsWorkspaceGeneralRouteImport } from './routes/_app/settings/workspace/general'
import { Route as AppSettingsWorkspaceEmailTemplatesRouteImport } from './routes/_app/settings/workspace/email-templates'
import { Route as AppSettingsWorkspaceDomainsRouteImport } from './routes/_app/settings/workspace/domains'
import { Route as AppSecurityThreatsRateLimitsRouteImport } from './routes/_app/security/threats/rate-limits'
import { Route as AppSecurityThreatsIpAllowlistRouteImport } from './routes/_app/security/threats/ip-allowlist'
import { Route as AppSecurityThreatsBotsRouteImport } from './routes/_app/security/threats/bots'
import { Route as AppSecurityThreatsAnomaliesRouteImport } from './routes/_app/security/threats/anomalies'
import { Route as AppSecurityComplianceSoc2RouteImport } from './routes/_app/security/compliance/soc2'
import { Route as AppSecurityComplianceRetentionRouteImport } from './routes/_app/security/compliance/retention'
import { Route as AppSecurityComplianceIso27001RouteImport } from './routes/_app/security/compliance/iso27001'
import { Route as AppSecurityComplianceGdprRouteImport } from './routes/_app/security/compliance/gdpr'
import { Route as AppDeveloperWebhooksIdRouteImport } from './routes/_app/developer/webhooks.$id'
import { Route as AppAuthMfaTotpRouteImport } from './routes/_app/auth/mfa/totp'
import { Route as AppAuthMfaSmsEmailRouteImport } from './routes/_app/auth/mfa/sms-email'
import { Route as AppAuthMfaRecoveryCodesRouteImport } from './routes/_app/auth/mfa/recovery-codes'
import { Route as AppAuthLoginMethodsPasswordlessRouteImport } from './routes/_app/auth/login-methods/passwordless'
import { Route as AppAuthLoginMethodsPasswordRouteImport } from './routes/_app/auth/login-methods/password'
import { Route as AppAuthLoginMethodsPasskeysRouteImport } from './routes/_app/auth/login-methods/passkeys'
import { Route as AppAuthLoginMethodsMagicLinksRouteImport } from './routes/_app/auth/login-methods/magic-links'
import { Route as AppAuthConnectionsScimRouteImport } from './routes/_app/auth/connections/scim'
import { Route as AppAuthConnectionsSamlRouteImport } from './routes/_app/auth/connections/saml'
import { Route as AppAuthConnectionsOidcRouteImport } from './routes/_app/auth/connections/oidc'
import { Route as AppAuthConnectionsLdapRouteImport } from './routes/_app/auth/connections/ldap'
import { Route as AppAuthApiTokensRouteImport } from './routes/_app/auth/api/tokens'
import { Route as AppAuthApiSecretsRouteImport } from './routes/_app/auth/api/secrets'
import { Route as AppAuthApiMachineIdentitiesRouteImport } from './routes/_app/auth/api/machine-identities'
import { Route as AppAuthApiKeysRouteImport } from './routes/_app/auth/api/keys'
import { Route as AppAccessRolesRoleIdRouteImport } from './routes/_app/access/roles.$roleId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AccountRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersSessionsRoute = AppUsersSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersInvitationsRoute = AppUsersInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersImportRoute = AppUsersImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersDeletedRoute = AppUsersDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/settings/branding',
  path: '/settings/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSecuritySessionsRoute = AppSecuritySessionsRouteImport.update({
  id: '/security/sessions',
  path: '/security/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRateLimitsRoute = AppSecurityRateLimitsRouteImport.update({
  id: '/security/rate-limits',
  path: '/security/rate-limits',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityAuditLogsRoute = AppSecurityAuditLogsRouteImport.update({
  id: '/security/audit-logs',
  path: '/security/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsTenantsRoute = AppOrganizationsTenantsRouteImport.update({
  id: '/organizations/tenants',
  path: '/organizations/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsMembersRoute = AppOrganizationsMembersRouteImport.update({
  id: '/organizations/members',
  path: '/organizations/members',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperWebhooksRoute = AppDeveloperWebhooksRouteImport.update({
  id: '/developer/webhooks',
  path: '/developer/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperInfrastructureRoute =
  AppDeveloperInfrastructureRouteImport.update({
    id: '/developer/infrastructure',
    path: '/developer/infrastructure',
    getParentRoute: () => AppRoute,
  } as any)
const AppDeveloperBotsRoute = AppDeveloperBotsRouteImport.update({
  id: '/developer/bots',
  path: '/developer/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthSocialRoute = AppAuthSocialRouteImport.update({
  id: '/auth/social',
  path: '/auth/social',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRolesRoute = AppAccessRolesRouteImport.update({
  id: '/access/roles',
  path: '/access/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessResourcesRoute = AppAccessResourcesRouteImport.update({
  id: '/access/resources',
  path: '/access/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessPoliciesRoute = AppAccessPoliciesRouteImport.update({
  id: '/access/policies',
  path: '/access/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessPermissionsRoute = AppAccessPermissionsRouteImport.update({
  id: '/access/permissions',
  path: '/access/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWorkspaceGeneralRoute =
  AppSettingsWorkspaceGeneralRouteImport.update({
    id: '/settings/workspace/general',
    path: '/settings/workspace/general',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsWorkspaceEmailTemplatesRoute =
  AppSettingsWorkspaceEmailTemplatesRouteImport.update({
    id: '/settings/workspace/email-templates',
    path: '/settings/workspace/email-templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsWorkspaceDomainsRoute =
  AppSettingsWorkspaceDomainsRouteImport.update({
    id: '/settings/workspace/domains',
    path: '/settings/workspace/domains',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsRateLimitsRoute =
  AppSecurityThreatsRateLimitsRouteImport.update({
    id: '/security/threats/rate-limits',
    path: '/security/threats/rate-limits',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsIpAllowlistRoute =
  AppSecurityThreatsIpAllowlistRouteImport.update({
    id: '/security/threats/ip-allowlist',
    path: '/security/threats/ip-allowlist',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsBotsRoute = AppSecurityThreatsBotsRouteImport.update({
  id: '/security/threats/bots',
  path: '/security/threats/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityThreatsAnomaliesRoute =
  AppSecurityThreatsAnomaliesRouteImport.update({
    id: '/security/threats/anomalies',
    path: '/security/threats/anomalies',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceSoc2Route =
  AppSecurityComplianceSoc2RouteImport.update({
    id: '/security/compliance/soc2',
    path: '/security/compliance/soc2',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceRetentionRoute =
  AppSecurityComplianceRetentionRouteImport.update({
    id: '/security/compliance/retention',
    path: '/security/compliance/retention',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceIso27001Route =
  AppSecurityComplianceIso27001RouteImport.update({
    id: '/security/compliance/iso27001',
    path: '/security/compliance/iso27001',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceGdprRoute =
  AppSecurityComplianceGdprRouteImport.update({
    id: '/security/compliance/gdpr',
    path: '/security/compliance/gdpr',
    getParentRoute: () => AppRoute,
  } as any)
const AppDeveloperWebhooksIdRoute = AppDeveloperWebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDeveloperWebhooksRoute,
} as any)
const AppAuthMfaTotpRoute = AppAuthMfaTotpRouteImport.update({
  id: '/auth/mfa/totp',
  path: '/auth/mfa/totp',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthMfaSmsEmailRoute = AppAuthMfaSmsEmailRouteImport.update({
  id: '/auth/mfa/sms-email',
  path: '/auth/mfa/sms-email',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthMfaRecoveryCodesRoute = AppAuthMfaRecoveryCodesRouteImport.update({
  id: '/auth/mfa/recovery-codes',
  path: '/auth/mfa/recovery-codes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginMethodsPasswordlessRoute =
  AppAuthLoginMethodsPasswordlessRouteImport.update({
    id: '/auth/login-methods/passwordless',
    path: '/auth/login-methods/passwordless',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsPasswordRoute =
  AppAuthLoginMethodsPasswordRouteImport.update({
    id: '/auth/login-methods/password',
    path: '/auth/login-methods/password',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsPasskeysRoute =
  AppAuthLoginMethodsPasskeysRouteImport.update({
    id: '/auth/login-methods/passkeys',
    path: '/auth/login-methods/passkeys',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsMagicLinksRoute =
  AppAuthLoginMethodsMagicLinksRouteImport.update({
    id: '/auth/login-methods/magic-links',
    path: '/auth/login-methods/magic-links',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthConnectionsScimRoute = AppAuthConnectionsScimRouteImport.update({
  id: '/auth/connections/scim',
  path: '/auth/connections/scim',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsSamlRoute = AppAuthConnectionsSamlRouteImport.update({
  id: '/auth/connections/saml',
  path: '/auth/connections/saml',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsOidcRoute = AppAuthConnectionsOidcRouteImport.update({
  id: '/auth/connections/oidc',
  path: '/auth/connections/oidc',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsLdapRoute = AppAuthConnectionsLdapRouteImport.update({
  id: '/auth/connections/ldap',
  path: '/auth/connections/ldap',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiTokensRoute = AppAuthApiTokensRouteImport.update({
  id: '/auth/api/tokens',
  path: '/auth/api/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiSecretsRoute = AppAuthApiSecretsRouteImport.update({
  id: '/auth/api/secrets',
  path: '/auth/api/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiMachineIdentitiesRoute =
  AppAuthApiMachineIdentitiesRouteImport.update({
    id: '/auth/api/machine-identities',
    path: '/auth/api/machine-identities',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthApiKeysRoute = AppAuthApiKeysRouteImport.update({
  id: '/auth/api/keys',
  path: '/auth/api/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRolesRoleIdRoute = AppAccessRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppAccessRolesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/invitations': typeof AppInvitationsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/magic': typeof AuthMagicRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/access/permissions': typeof AppAccessPermissionsRoute
  '/access/policies': typeof AppAccessPoliciesRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/access/roles': typeof AppAccessRolesRouteWithChildren
  '/auth/social': typeof AppAuthSocialRoute
  '/developer/bots': typeof AppDeveloperBotsRoute
  '/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/developer/webhooks': typeof AppDeveloperWebhooksRouteWithChildren
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/security/sessions': typeof AppSecuritySessionsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/users/import': typeof AppUsersImportRoute
  '/users/invitations': typeof AppUsersInvitationsRoute
  '/users/sessions': typeof AppUsersSessionsRoute
  '/access/roles/$roleId': typeof AppAccessRolesRoleIdRoute
  '/auth/api/keys': typeof AppAuthApiKeysRoute
  '/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/auth/connections/oidc': typeof AppAuthConnectionsOidcRoute
  '/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/invitations': typeof AppInvitationsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/magic': typeof AuthMagicRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/access/permissions': typeof AppAccessPermissionsRoute
  '/access/policies': typeof AppAccessPoliciesRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/access/roles': typeof AppAccessRolesRouteWithChildren
  '/auth/social': typeof AppAuthSocialRoute
  '/developer/bots': typeof AppDeveloperBotsRoute
  '/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/developer/webhooks': typeof AppDeveloperWebhooksRouteWithChildren
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/security/sessions': typeof AppSecuritySessionsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/users/import': typeof AppUsersImportRoute
  '/users/invitations': typeof AppUsersInvitationsRoute
  '/users/sessions': typeof AppUsersSessionsRoute
  '/access/roles/$roleId': typeof AppAccessRolesRoleIdRoute
  '/auth/api/keys': typeof AppAuthApiKeysRoute
  '/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/auth/connections/oidc': typeof AppAuthConnectionsOidcRoute
  '/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/invitations': typeof AppInvitationsRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/magic': typeof AuthMagicRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/_app/access/permissions': typeof AppAccessPermissionsRoute
  '/_app/access/policies': typeof AppAccessPoliciesRoute
  '/_app/access/resources': typeof AppAccessResourcesRoute
  '/_app/access/roles': typeof AppAccessRolesRouteWithChildren
  '/_app/auth/social': typeof AppAuthSocialRoute
  '/_app/developer/bots': typeof AppDeveloperBotsRoute
  '/_app/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/_app/developer/webhooks': typeof AppDeveloperWebhooksRouteWithChildren
  '/_app/organizations/members': typeof AppOrganizationsMembersRoute
  '/_app/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/_app/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/_app/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/_app/security/sessions': typeof AppSecuritySessionsRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/branding': typeof AppSettingsBrandingRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/deleted': typeof AppUsersDeletedRoute
  '/_app/users/import': typeof AppUsersImportRoute
  '/_app/users/invitations': typeof AppUsersInvitationsRoute
  '/_app/users/sessions': typeof AppUsersSessionsRoute
  '/_app/access/roles/$roleId': typeof AppAccessRolesRoleIdRoute
  '/_app/auth/api/keys': typeof AppAuthApiKeysRoute
  '/_app/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/_app/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/_app/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/_app/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/_app/auth/connections/oidc': typeof AppAuthConnectionsOidcRoute
  '/_app/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/_app/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/_app/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/_app/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/_app/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/_app/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/_app/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/_app/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/_app/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/_app/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/_app/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/_app/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/_app/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/_app/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/_app/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/_app/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/_app/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/_app/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/_app/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/_app/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/_app/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/dashboard'
    | '/groups'
    | '/invitations'
    | '/users'
    | '/forgot-password'
    | '/magic'
    | '/sign-in'
    | '/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/access/permissions'
    | '/access/policies'
    | '/access/resources'
    | '/access/roles'
    | '/auth/social'
    | '/developer/bots'
    | '/developer/infrastructure'
    | '/developer/webhooks'
    | '/organizations/members'
    | '/organizations/tenants'
    | '/security/audit-logs'
    | '/security/rate-limits'
    | '/security/sessions'
    | '/settings/billing'
    | '/settings/branding'
    | '/users/$userId'
    | '/users/deleted'
    | '/users/import'
    | '/users/invitations'
    | '/users/sessions'
    | '/access/roles/$roleId'
    | '/auth/api/keys'
    | '/auth/api/machine-identities'
    | '/auth/api/secrets'
    | '/auth/api/tokens'
    | '/auth/connections/ldap'
    | '/auth/connections/oidc'
    | '/auth/connections/saml'
    | '/auth/connections/scim'
    | '/auth/login-methods/magic-links'
    | '/auth/login-methods/passkeys'
    | '/auth/login-methods/password'
    | '/auth/login-methods/passwordless'
    | '/auth/mfa/recovery-codes'
    | '/auth/mfa/sms-email'
    | '/auth/mfa/totp'
    | '/developer/webhooks/$id'
    | '/security/compliance/gdpr'
    | '/security/compliance/iso27001'
    | '/security/compliance/retention'
    | '/security/compliance/soc2'
    | '/security/threats/anomalies'
    | '/security/threats/bots'
    | '/security/threats/ip-allowlist'
    | '/security/threats/rate-limits'
    | '/settings/workspace/domains'
    | '/settings/workspace/email-templates'
    | '/settings/workspace/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/dashboard'
    | '/groups'
    | '/invitations'
    | '/users'
    | '/forgot-password'
    | '/magic'
    | '/sign-in'
    | '/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/access/permissions'
    | '/access/policies'
    | '/access/resources'
    | '/access/roles'
    | '/auth/social'
    | '/developer/bots'
    | '/developer/infrastructure'
    | '/developer/webhooks'
    | '/organizations/members'
    | '/organizations/tenants'
    | '/security/audit-logs'
    | '/security/rate-limits'
    | '/security/sessions'
    | '/settings/billing'
    | '/settings/branding'
    | '/users/$userId'
    | '/users/deleted'
    | '/users/import'
    | '/users/invitations'
    | '/users/sessions'
    | '/access/roles/$roleId'
    | '/auth/api/keys'
    | '/auth/api/machine-identities'
    | '/auth/api/secrets'
    | '/auth/api/tokens'
    | '/auth/connections/ldap'
    | '/auth/connections/oidc'
    | '/auth/connections/saml'
    | '/auth/connections/scim'
    | '/auth/login-methods/magic-links'
    | '/auth/login-methods/passkeys'
    | '/auth/login-methods/password'
    | '/auth/login-methods/passwordless'
    | '/auth/mfa/recovery-codes'
    | '/auth/mfa/sms-email'
    | '/auth/mfa/totp'
    | '/developer/webhooks/$id'
    | '/security/compliance/gdpr'
    | '/security/compliance/iso27001'
    | '/security/compliance/retention'
    | '/security/compliance/soc2'
    | '/security/threats/anomalies'
    | '/security/threats/bots'
    | '/security/threats/ip-allowlist'
    | '/security/threats/rate-limits'
    | '/settings/workspace/domains'
    | '/settings/workspace/email-templates'
    | '/settings/workspace/general'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/account'
    | '/_app/$'
    | '/_app/activity'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/groups'
    | '/_app/invitations'
    | '/_app/users'
    | '/_auth/forgot-password'
    | '/_auth/magic'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/_app/access/permissions'
    | '/_app/access/policies'
    | '/_app/access/resources'
    | '/_app/access/roles'
    | '/_app/auth/social'
    | '/_app/developer/bots'
    | '/_app/developer/infrastructure'
    | '/_app/developer/webhooks'
    | '/_app/organizations/members'
    | '/_app/organizations/tenants'
    | '/_app/security/audit-logs'
    | '/_app/security/rate-limits'
    | '/_app/security/sessions'
    | '/_app/settings/billing'
    | '/_app/settings/branding'
    | '/_app/users/$userId'
    | '/_app/users/deleted'
    | '/_app/users/import'
    | '/_app/users/invitations'
    | '/_app/users/sessions'
    | '/_app/access/roles/$roleId'
    | '/_app/auth/api/keys'
    | '/_app/auth/api/machine-identities'
    | '/_app/auth/api/secrets'
    | '/_app/auth/api/tokens'
    | '/_app/auth/connections/ldap'
    | '/_app/auth/connections/oidc'
    | '/_app/auth/connections/saml'
    | '/_app/auth/connections/scim'
    | '/_app/auth/login-methods/magic-links'
    | '/_app/auth/login-methods/passkeys'
    | '/_app/auth/login-methods/password'
    | '/_app/auth/login-methods/passwordless'
    | '/_app/auth/mfa/recovery-codes'
    | '/_app/auth/mfa/sms-email'
    | '/_app/auth/mfa/totp'
    | '/_app/developer/webhooks/$id'
    | '/_app/security/compliance/gdpr'
    | '/_app/security/compliance/iso27001'
    | '/_app/security/compliance/retention'
    | '/_app/security/compliance/soc2'
    | '/_app/security/threats/anomalies'
    | '/_app/security/threats/bots'
    | '/_app/security/threats/ip-allowlist'
    | '/_app/security/threats/rate-limits'
    | '/_app/settings/workspace/domains'
    | '/_app/settings/workspace/email-templates'
    | '/_app/settings/workspace/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/data': {
      id: '/account/data'
      path: '/data'
      fullPath: '/account/data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/magic': {
      id: '/_auth/magic'
      path: '/magic'
      fullPath: '/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invitations': {
      id: '/_app/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/sessions': {
      id: '/_app/users/sessions'
      path: '/sessions'
      fullPath: '/users/sessions'
      preLoaderRoute: typeof AppUsersSessionsRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/invitations': {
      id: '/_app/users/invitations'
      path: '/invitations'
      fullPath: '/users/invitations'
      preLoaderRoute: typeof AppUsersInvitationsRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/import': {
      id: '/_app/users/import'
      path: '/import'
      fullPath: '/users/import'
      preLoaderRoute: typeof AppUsersImportRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/deleted': {
      id: '/_app/users/deleted'
      path: '/deleted'
      fullPath: '/users/deleted'
      preLoaderRoute: typeof AppUsersDeletedRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/settings/branding': {
      id: '/_app/settings/branding'
      path: '/settings/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/sessions': {
      id: '/_app/security/sessions'
      path: '/security/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof AppSecuritySessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/rate-limits': {
      id: '/_app/security/rate-limits'
      path: '/security/rate-limits'
      fullPath: '/security/rate-limits'
      preLoaderRoute: typeof AppSecurityRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/audit-logs': {
      id: '/_app/security/audit-logs'
      path: '/security/audit-logs'
      fullPath: '/security/audit-logs'
      preLoaderRoute: typeof AppSecurityAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/tenants': {
      id: '/_app/organizations/tenants'
      path: '/organizations/tenants'
      fullPath: '/organizations/tenants'
      preLoaderRoute: typeof AppOrganizationsTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/members': {
      id: '/_app/organizations/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AppOrganizationsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/webhooks': {
      id: '/_app/developer/webhooks'
      path: '/developer/webhooks'
      fullPath: '/developer/webhooks'
      preLoaderRoute: typeof AppDeveloperWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/infrastructure': {
      id: '/_app/developer/infrastructure'
      path: '/developer/infrastructure'
      fullPath: '/developer/infrastructure'
      preLoaderRoute: typeof AppDeveloperInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/bots': {
      id: '/_app/developer/bots'
      path: '/developer/bots'
      fullPath: '/developer/bots'
      preLoaderRoute: typeof AppDeveloperBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/social': {
      id: '/_app/auth/social'
      path: '/auth/social'
      fullPath: '/auth/social'
      preLoaderRoute: typeof AppAuthSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/roles': {
      id: '/_app/access/roles'
      path: '/access/roles'
      fullPath: '/access/roles'
      preLoaderRoute: typeof AppAccessRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/resources': {
      id: '/_app/access/resources'
      path: '/access/resources'
      fullPath: '/access/resources'
      preLoaderRoute: typeof AppAccessResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/policies': {
      id: '/_app/access/policies'
      path: '/access/policies'
      fullPath: '/access/policies'
      preLoaderRoute: typeof AppAccessPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/permissions': {
      id: '/_app/access/permissions'
      path: '/access/permissions'
      fullPath: '/access/permissions'
      preLoaderRoute: typeof AppAccessPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/general': {
      id: '/_app/settings/workspace/general'
      path: '/settings/workspace/general'
      fullPath: '/settings/workspace/general'
      preLoaderRoute: typeof AppSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/email-templates': {
      id: '/_app/settings/workspace/email-templates'
      path: '/settings/workspace/email-templates'
      fullPath: '/settings/workspace/email-templates'
      preLoaderRoute: typeof AppSettingsWorkspaceEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/domains': {
      id: '/_app/settings/workspace/domains'
      path: '/settings/workspace/domains'
      fullPath: '/settings/workspace/domains'
      preLoaderRoute: typeof AppSettingsWorkspaceDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/rate-limits': {
      id: '/_app/security/threats/rate-limits'
      path: '/security/threats/rate-limits'
      fullPath: '/security/threats/rate-limits'
      preLoaderRoute: typeof AppSecurityThreatsRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/ip-allowlist': {
      id: '/_app/security/threats/ip-allowlist'
      path: '/security/threats/ip-allowlist'
      fullPath: '/security/threats/ip-allowlist'
      preLoaderRoute: typeof AppSecurityThreatsIpAllowlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/bots': {
      id: '/_app/security/threats/bots'
      path: '/security/threats/bots'
      fullPath: '/security/threats/bots'
      preLoaderRoute: typeof AppSecurityThreatsBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/anomalies': {
      id: '/_app/security/threats/anomalies'
      path: '/security/threats/anomalies'
      fullPath: '/security/threats/anomalies'
      preLoaderRoute: typeof AppSecurityThreatsAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/soc2': {
      id: '/_app/security/compliance/soc2'
      path: '/security/compliance/soc2'
      fullPath: '/security/compliance/soc2'
      preLoaderRoute: typeof AppSecurityComplianceSoc2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/retention': {
      id: '/_app/security/compliance/retention'
      path: '/security/compliance/retention'
      fullPath: '/security/compliance/retention'
      preLoaderRoute: typeof AppSecurityComplianceRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/iso27001': {
      id: '/_app/security/compliance/iso27001'
      path: '/security/compliance/iso27001'
      fullPath: '/security/compliance/iso27001'
      preLoaderRoute: typeof AppSecurityComplianceIso27001RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/gdpr': {
      id: '/_app/security/compliance/gdpr'
      path: '/security/compliance/gdpr'
      fullPath: '/security/compliance/gdpr'
      preLoaderRoute: typeof AppSecurityComplianceGdprRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/webhooks/$id': {
      id: '/_app/developer/webhooks/$id'
      path: '/$id'
      fullPath: '/developer/webhooks/$id'
      preLoaderRoute: typeof AppDeveloperWebhooksIdRouteImport
      parentRoute: typeof AppDeveloperWebhooksRoute
    }
    '/_app/auth/mfa/totp': {
      id: '/_app/auth/mfa/totp'
      path: '/auth/mfa/totp'
      fullPath: '/auth/mfa/totp'
      preLoaderRoute: typeof AppAuthMfaTotpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/mfa/sms-email': {
      id: '/_app/auth/mfa/sms-email'
      path: '/auth/mfa/sms-email'
      fullPath: '/auth/mfa/sms-email'
      preLoaderRoute: typeof AppAuthMfaSmsEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/mfa/recovery-codes': {
      id: '/_app/auth/mfa/recovery-codes'
      path: '/auth/mfa/recovery-codes'
      fullPath: '/auth/mfa/recovery-codes'
      preLoaderRoute: typeof AppAuthMfaRecoveryCodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/passwordless': {
      id: '/_app/auth/login-methods/passwordless'
      path: '/auth/login-methods/passwordless'
      fullPath: '/auth/login-methods/passwordless'
      preLoaderRoute: typeof AppAuthLoginMethodsPasswordlessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/password': {
      id: '/_app/auth/login-methods/password'
      path: '/auth/login-methods/password'
      fullPath: '/auth/login-methods/password'
      preLoaderRoute: typeof AppAuthLoginMethodsPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/passkeys': {
      id: '/_app/auth/login-methods/passkeys'
      path: '/auth/login-methods/passkeys'
      fullPath: '/auth/login-methods/passkeys'
      preLoaderRoute: typeof AppAuthLoginMethodsPasskeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/magic-links': {
      id: '/_app/auth/login-methods/magic-links'
      path: '/auth/login-methods/magic-links'
      fullPath: '/auth/login-methods/magic-links'
      preLoaderRoute: typeof AppAuthLoginMethodsMagicLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/scim': {
      id: '/_app/auth/connections/scim'
      path: '/auth/connections/scim'
      fullPath: '/auth/connections/scim'
      preLoaderRoute: typeof AppAuthConnectionsScimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/saml': {
      id: '/_app/auth/connections/saml'
      path: '/auth/connections/saml'
      fullPath: '/auth/connections/saml'
      preLoaderRoute: typeof AppAuthConnectionsSamlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/oidc': {
      id: '/_app/auth/connections/oidc'
      path: '/auth/connections/oidc'
      fullPath: '/auth/connections/oidc'
      preLoaderRoute: typeof AppAuthConnectionsOidcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/ldap': {
      id: '/_app/auth/connections/ldap'
      path: '/auth/connections/ldap'
      fullPath: '/auth/connections/ldap'
      preLoaderRoute: typeof AppAuthConnectionsLdapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/tokens': {
      id: '/_app/auth/api/tokens'
      path: '/auth/api/tokens'
      fullPath: '/auth/api/tokens'
      preLoaderRoute: typeof AppAuthApiTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/secrets': {
      id: '/_app/auth/api/secrets'
      path: '/auth/api/secrets'
      fullPath: '/auth/api/secrets'
      preLoaderRoute: typeof AppAuthApiSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/machine-identities': {
      id: '/_app/auth/api/machine-identities'
      path: '/auth/api/machine-identities'
      fullPath: '/auth/api/machine-identities'
      preLoaderRoute: typeof AppAuthApiMachineIdentitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/keys': {
      id: '/_app/auth/api/keys'
      path: '/auth/api/keys'
      fullPath: '/auth/api/keys'
      preLoaderRoute: typeof AppAuthApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/roles/$roleId': {
      id: '/_app/access/roles/$roleId'
      path: '/$roleId'
      fullPath: '/access/roles/$roleId'
      preLoaderRoute: typeof AppAccessRolesRoleIdRouteImport
      parentRoute: typeof AppAccessRolesRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersDeletedRoute: typeof AppUsersDeletedRoute
  AppUsersImportRoute: typeof AppUsersImportRoute
  AppUsersInvitationsRoute: typeof AppUsersInvitationsRoute
  AppUsersSessionsRoute: typeof AppUsersSessionsRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersDeletedRoute: AppUsersDeletedRoute,
  AppUsersImportRoute: AppUsersImportRoute,
  AppUsersInvitationsRoute: AppUsersInvitationsRoute,
  AppUsersSessionsRoute: AppUsersSessionsRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppAccessRolesRouteChildren {
  AppAccessRolesRoleIdRoute: typeof AppAccessRolesRoleIdRoute
}

const AppAccessRolesRouteChildren: AppAccessRolesRouteChildren = {
  AppAccessRolesRoleIdRoute: AppAccessRolesRoleIdRoute,
}

const AppAccessRolesRouteWithChildren = AppAccessRolesRoute._addFileChildren(
  AppAccessRolesRouteChildren,
)

interface AppDeveloperWebhooksRouteChildren {
  AppDeveloperWebhooksIdRoute: typeof AppDeveloperWebhooksIdRoute
}

const AppDeveloperWebhooksRouteChildren: AppDeveloperWebhooksRouteChildren = {
  AppDeveloperWebhooksIdRoute: AppDeveloperWebhooksIdRoute,
}

const AppDeveloperWebhooksRouteWithChildren =
  AppDeveloperWebhooksRoute._addFileChildren(AppDeveloperWebhooksRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppAccessPermissionsRoute: typeof AppAccessPermissionsRoute
  AppAccessPoliciesRoute: typeof AppAccessPoliciesRoute
  AppAccessResourcesRoute: typeof AppAccessResourcesRoute
  AppAccessRolesRoute: typeof AppAccessRolesRouteWithChildren
  AppAuthSocialRoute: typeof AppAuthSocialRoute
  AppDeveloperBotsRoute: typeof AppDeveloperBotsRoute
  AppDeveloperInfrastructureRoute: typeof AppDeveloperInfrastructureRoute
  AppDeveloperWebhooksRoute: typeof AppDeveloperWebhooksRouteWithChildren
  AppOrganizationsMembersRoute: typeof AppOrganizationsMembersRoute
  AppOrganizationsTenantsRoute: typeof AppOrganizationsTenantsRoute
  AppSecurityAuditLogsRoute: typeof AppSecurityAuditLogsRoute
  AppSecurityRateLimitsRoute: typeof AppSecurityRateLimitsRoute
  AppSecuritySessionsRoute: typeof AppSecuritySessionsRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
  AppAuthApiKeysRoute: typeof AppAuthApiKeysRoute
  AppAuthApiMachineIdentitiesRoute: typeof AppAuthApiMachineIdentitiesRoute
  AppAuthApiSecretsRoute: typeof AppAuthApiSecretsRoute
  AppAuthApiTokensRoute: typeof AppAuthApiTokensRoute
  AppAuthConnectionsLdapRoute: typeof AppAuthConnectionsLdapRoute
  AppAuthConnectionsOidcRoute: typeof AppAuthConnectionsOidcRoute
  AppAuthConnectionsSamlRoute: typeof AppAuthConnectionsSamlRoute
  AppAuthConnectionsScimRoute: typeof AppAuthConnectionsScimRoute
  AppAuthLoginMethodsMagicLinksRoute: typeof AppAuthLoginMethodsMagicLinksRoute
  AppAuthLoginMethodsPasskeysRoute: typeof AppAuthLoginMethodsPasskeysRoute
  AppAuthLoginMethodsPasswordRoute: typeof AppAuthLoginMethodsPasswordRoute
  AppAuthLoginMethodsPasswordlessRoute: typeof AppAuthLoginMethodsPasswordlessRoute
  AppAuthMfaRecoveryCodesRoute: typeof AppAuthMfaRecoveryCodesRoute
  AppAuthMfaSmsEmailRoute: typeof AppAuthMfaSmsEmailRoute
  AppAuthMfaTotpRoute: typeof AppAuthMfaTotpRoute
  AppSecurityComplianceGdprRoute: typeof AppSecurityComplianceGdprRoute
  AppSecurityComplianceIso27001Route: typeof AppSecurityComplianceIso27001Route
  AppSecurityComplianceRetentionRoute: typeof AppSecurityComplianceRetentionRoute
  AppSecurityComplianceSoc2Route: typeof AppSecurityComplianceSoc2Route
  AppSecurityThreatsAnomaliesRoute: typeof AppSecurityThreatsAnomaliesRoute
  AppSecurityThreatsBotsRoute: typeof AppSecurityThreatsBotsRoute
  AppSecurityThreatsIpAllowlistRoute: typeof AppSecurityThreatsIpAllowlistRoute
  AppSecurityThreatsRateLimitsRoute: typeof AppSecurityThreatsRateLimitsRoute
  AppSettingsWorkspaceDomainsRoute: typeof AppSettingsWorkspaceDomainsRoute
  AppSettingsWorkspaceEmailTemplatesRoute: typeof AppSettingsWorkspaceEmailTemplatesRoute
  AppSettingsWorkspaceGeneralRoute: typeof AppSettingsWorkspaceGeneralRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppAccessPermissionsRoute: AppAccessPermissionsRoute,
  AppAccessPoliciesRoute: AppAccessPoliciesRoute,
  AppAccessResourcesRoute: AppAccessResourcesRoute,
  AppAccessRolesRoute: AppAccessRolesRouteWithChildren,
  AppAuthSocialRoute: AppAuthSocialRoute,
  AppDeveloperBotsRoute: AppDeveloperBotsRoute,
  AppDeveloperInfrastructureRoute: AppDeveloperInfrastructureRoute,
  AppDeveloperWebhooksRoute: AppDeveloperWebhooksRouteWithChildren,
  AppOrganizationsMembersRoute: AppOrganizationsMembersRoute,
  AppOrganizationsTenantsRoute: AppOrganizationsTenantsRoute,
  AppSecurityAuditLogsRoute: AppSecurityAuditLogsRoute,
  AppSecurityRateLimitsRoute: AppSecurityRateLimitsRoute,
  AppSecuritySessionsRoute: AppSecuritySessionsRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
  AppAuthApiKeysRoute: AppAuthApiKeysRoute,
  AppAuthApiMachineIdentitiesRoute: AppAuthApiMachineIdentitiesRoute,
  AppAuthApiSecretsRoute: AppAuthApiSecretsRoute,
  AppAuthApiTokensRoute: AppAuthApiTokensRoute,
  AppAuthConnectionsLdapRoute: AppAuthConnectionsLdapRoute,
  AppAuthConnectionsOidcRoute: AppAuthConnectionsOidcRoute,
  AppAuthConnectionsSamlRoute: AppAuthConnectionsSamlRoute,
  AppAuthConnectionsScimRoute: AppAuthConnectionsScimRoute,
  AppAuthLoginMethodsMagicLinksRoute: AppAuthLoginMethodsMagicLinksRoute,
  AppAuthLoginMethodsPasskeysRoute: AppAuthLoginMethodsPasskeysRoute,
  AppAuthLoginMethodsPasswordRoute: AppAuthLoginMethodsPasswordRoute,
  AppAuthLoginMethodsPasswordlessRoute: AppAuthLoginMethodsPasswordlessRoute,
  AppAuthMfaRecoveryCodesRoute: AppAuthMfaRecoveryCodesRoute,
  AppAuthMfaSmsEmailRoute: AppAuthMfaSmsEmailRoute,
  AppAuthMfaTotpRoute: AppAuthMfaTotpRoute,
  AppSecurityComplianceGdprRoute: AppSecurityComplianceGdprRoute,
  AppSecurityComplianceIso27001Route: AppSecurityComplianceIso27001Route,
  AppSecurityComplianceRetentionRoute: AppSecurityComplianceRetentionRoute,
  AppSecurityComplianceSoc2Route: AppSecurityComplianceSoc2Route,
  AppSecurityThreatsAnomaliesRoute: AppSecurityThreatsAnomaliesRoute,
  AppSecurityThreatsBotsRoute: AppSecurityThreatsBotsRoute,
  AppSecurityThreatsIpAllowlistRoute: AppSecurityThreatsIpAllowlistRoute,
  AppSecurityThreatsRateLimitsRoute: AppSecurityThreatsRateLimitsRoute,
  AppSettingsWorkspaceDomainsRoute: AppSettingsWorkspaceDomainsRoute,
  AppSettingsWorkspaceEmailTemplatesRoute:
    AppSettingsWorkspaceEmailTemplatesRoute,
  AppSettingsWorkspaceGeneralRoute: AppSettingsWorkspaceGeneralRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicRoute: typeof AuthMagicRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicRoute: AuthMagicRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AccountRouteChildren {
  AccountDataRoute: typeof AccountDataRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDataRoute: AccountDataRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
